services:
  app:
    build: .
    command: bash start.sh
    restart: on-failure
    network_mode: "host"
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./downloads:/usr/src/app/downloads
      - ./thumbnails:/usr/src/app/thumbnails
      - ./accounts:/usr/src/app/accounts
      - ./tokens:/usr/src/app/tokens
      - ./rclone:/usr/src/app/rclone