services:
  - type: web
    name: leech-bot
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    region: oregon
    branch: master
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: OWNER_ID
        sync: false
      - key: TELEGRAM_API
        sync: false
      - key: TELEGRAM_HASH
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: BASE_URL
        fromService:
          type: web
          name: leech-bot
          property: host
      - key: BASE_URL_PORT
        value: 80
      - key: RCLONE_SERVE_PORT
        value: 8080
      - key: PORT
        value: 80
      - key: UPSTREAM_REPO
        value: https://github.com/beathindidubbed-lab/Leech-bot-2
      - key: UPSTREAM_BRANCH
        value: master
      - key: UPDATE_PKGS
        value: True
